name: daily-cron
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://logs-drain.vercel.app/api/batch' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'